module.exports.login = require('./login')
module.exports.register = require('./register')
module.exports.updateMyProfileData = require('./update-my-profile-data')
module.exports.getProfileData = require('./get-profile-data')
module.exports.get = require('./get')
